# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1

description: Common jobs for testing and building phoenix applications

executors:
  builder:
    docker:
      - image: cimg/elixir:1.16.0-erlang-26.2.1-node
      - image: cimg/postgres:14.12-alpine
    working_directory: ~/project

commands:
  install-deps:
    description: Installs mix and npm dependencies
    parameters:
      include-assets:
        type: boolean
        default: true
    steps:
      - run:
          name: Install hex
          command: mix local.hex --force
      - run:
          name: Install rebar
          command: mix local.rebar --force
      - run:
          name: Install mix deps
          command: mix deps.get
      - when:
          condition: << parameters.include-assets >>
          steps:
            - run:
                name: Install npm deps
                command: npm install --prefix=./assets

  mix-format:
    description: Validates code has been formatted with mix format
    steps:
      - run:
          name: Check elixir formatting
          command: mix format --check-formatted --dry-run

  mix-test:
    description: Runs all tests via mix
    steps:
      - run:
          name: Run tests
          command: MIX_ENV=test mix test --cover

jobs:
  check-formatting:
    executor: builder
    steps:
      - checkout
      - install-deps:
          include-assets: false
      - mix-format

  run-unit-tests:
    executor: builder
    steps:
      - checkout
      - install-deps:
          include-assets: false
      - mix-test

workflows:
  example:
    jobs:
      - check-formatting
      - run-unit-tests
